name: Main Multi-Workflow Controller

on:
  push:
    branches:
      - main

jobs:
  # This calls block_action.yaml file
  run-block-action:
    uses: ./.github/workflows/block_action.yml

      # This calls mute_action.yaml file
  run-block-action:
    uses: ./.github/workflows/mute_action.yml

  # This calls static.yml file
  run-static-site:
    uses: ./.github/workflows/static.yml

