name: Main Multi-Workflow Controller

on:
  push:
    branches:
      - main

jobs:
  # This calls quora_all.yaml file
  run-quora-all:
    uses: ./.github/workflows/quora_all.yml

     # This calls static.yml file
  run-static-site:
    uses: ./.github/workflows/static.yml

