name: Mute Space Action Quora

on:
  push:
    branches:
      - main
    paths:
      - 'full/spacemute.js'
 # This allows the workflow to be called from main.yml
  workflow_call:

jobs:
  bookmarklet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Bookmarklet Generator Action
        uses: ulrischa/js_to_bookmarklet_action@v1
        with:
          source_js_file: 'full/spacemute.js'
          target_html_file: 'bookmarklet/install_page.htm'
          target_element_id: 'mute'
          commit_message: 'Update mute bookmarklet link'

      - name: Debug Files and Environment
        run: |
          ls -la .
          cat full/spacemute.js
          cat bookmarklet/install_page.htm
        shell: bash
