name: Deploy Static Site

on:
  workflow_call:  # <-- This is the "Prereq E1" change

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Granting necessary permissions for GitHub Pages
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/setup-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Double check this folder exists in your repo!
          path: './bookmarklet'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
